package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA



/**
 * CategoryChild generated by hbm2java
 */
public class CategoryChild  implements java.io.Serializable {


     private String categoryChildId;
     private String categoryId;
     private String categoryChildName;
     private Set products = new HashSet(0);
     private Set categorysubs = new HashSet(0);
   

	public CategoryChild() {
    }

    public CategoryChild(String categoryChildId, String categoryId, String categoryChildName) {
       this.categoryChildId = categoryChildId;
       this.categoryId = categoryId;
       this.categoryChildName = categoryChildName;
    }
    
    public CategoryChild(String categoryChildId, String categoryId, String categoryChildName, Set products, Set categorysubs) {
        this.categoryChildId = categoryChildId;
        this.categoryId = categoryId;
        this.categoryChildName = categoryChildName;
        this.products = products;
        this.categorysubs = categorysubs;
     }
   
    public String getCategoryChildId() {
        return this.categoryChildId;
    }
    
    public void setCategoryChildId(String categoryChildId) {
        this.categoryChildId = categoryChildId;
    }
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryChildName() {
        return this.categoryChildName;
    }
    
    public void setCategoryChildName(String categoryChildName) {
        this.categoryChildName = categoryChildName;
    }

    public Set getProducts() {
		return products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getCategorysubs() {
		return categorysubs;
	}

	public void setCategorysubs(Set categorysubs) {
		this.categorysubs = categorysubs;
	}


}


