package POJO;

import java.util.Date;
// Generated Sep 23, 2011 1:39:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Nganluong generated by hbm2java
 */
public class Nganluong  implements java.io.Serializable {


     private Integer nganLuongId;
     private String receiver;
     private String sellerAccount;
     private Date createDate;
     private Date updateDate;

    public Nganluong() {
    }

    public Nganluong(String receiver,String sellerAccount) {
       this.receiver = receiver;
       this.sellerAccount = sellerAccount;
    }
    
   
    public Nganluong( String receiver, String sellerAccount, Date createDate,
			Date updateDate) {
		this.receiver = receiver;
		this.sellerAccount = sellerAccount;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getNganLuongId() {
        return this.nganLuongId;
    }
    
    public void setNganLuongId(Integer nganLuongId) {
        this.nganLuongId = nganLuongId;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    
    public String getSellerAccount() {
        return this.sellerAccount;
    }
    
    public void setSellerAccount(String sellerAccount) {
        this.sellerAccount = sellerAccount;
    }

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}




}


