package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA



/**
 * Productphotos generated by hbm2java
 */
public class Productphotos  implements java.io.Serializable {


     private Integer productPhotoId;
     private String productPhotoName;
     private int productId;

    public Productphotos() {
    }

    public Productphotos(String productPhotoName, int productId) {
       this.productPhotoName = productPhotoName;
       this.productId = productId;
    }
   
    public Integer getProductPhotoId() {
        return this.productPhotoId;
    }
    
    public void setProductPhotoId(Integer productPhotoId) {
        this.productPhotoId = productPhotoId;
    }
    public String getProductPhotoName() {
        return this.productPhotoName;
    }
    
    public void setProductPhotoName(String productPhotoName) {
        this.productPhotoName = productPhotoName;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }




}


