package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private String size;
     private String color;
     private String detail;
     private int amount;
	 private String unit;
     private float price;
     private String categoryChildId;
     private String categorySubId;
     private int originId;
     private int productTypeId;
     private int manufacturerId;
	 private User user;
	 private Date uploadDate;
	 private Delivercost deliverCost;
     private Set productorderdetails = new HashSet(0);
     private Set productphotos = new HashSet(0);
     private Set promotions = new HashSet(0);
     private Set inventorys = new HashSet(0);
     private Set extensions = new HashSet(0);
     private Set options = new HashSet(0);

    
	public Products() {
  	}
	
    public Products(String productName, String size, String color, String detail, int amount, String unit, float price, String categoryChildId,String categorySubId, int manufacturerId, User user, Date uploadDate, int originId, int productTypeId,Delivercost deliverCost) {
        this.productName = productName;
        this.size = size;
		this.user = user;
        this.color = color;
        this.detail = detail;
        this.amount = amount;
        this.unit = unit;
        this.price = price;
        this.categoryChildId = categoryChildId;
        this.manufacturerId = manufacturerId;
		this.uploadDate = uploadDate;
		this.categorySubId = categorySubId;
		this.originId = originId;
		this.productTypeId = productTypeId;
		this.deliverCost=deliverCost;
    }
    public Products(String productName, String size, String color, String detail, int amount, String unit, float price, String categoryChildId,String categorySubId, int manufacturerId, User user, int originId, int productTypeId, Set productorderdetails, Date uploadDate, Set productphotos, Set promotions, Set inventorys, Set extensions) {
       this.productName = productName;
       this.size = size;
       this.color = color;
       this.detail = detail;
       this.amount = amount;
       this.unit = unit;
       this.price = price;
       this.categoryChildId = categoryChildId;
       this.manufacturerId = manufacturerId;
	   this.user = user;
	   this.uploadDate = uploadDate;
       this.productorderdetails = productorderdetails;
       this.productphotos = productphotos;
       this.promotions = promotions;
       this.categorySubId = categorySubId;
       this.originId = originId;
       this.productTypeId = productTypeId;
       this.inventorys = inventorys;
       this.extensions = extensions;
    }
   
    public Set getExtensions() {
		return extensions;
	}

	public void setExtensions(Set extensions) {
		this.extensions = extensions;
	}

	public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getCategoryChildId() {
        return this.categoryChildId;
    }
    
    public void setCategoryChildId(String categoryChildId) {
        this.categoryChildId = categoryChildId;
    }
    public int getManufacturerId() {
        return this.manufacturerId;
    }
    
    public void setManufacturerId(int manufacturerId) {
        this.manufacturerId = manufacturerId;
    }
	public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getProductorderdetails() {
        return this.productorderdetails;
    }
    
    public void setProductorderdetails(Set productorderdetails) {
        this.productorderdetails = productorderdetails;
    }

    public Date getUploadDate() {
		return uploadDate;
	 }
    public int getOriginId() {
		return originId;
	}

	public void setOriginId(int originId) {
		this.originId = originId;
	}

	public int getProductTypeId() {
		return productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}
	
	public Delivercost getDeliverCost() {
		return deliverCost;
	}

	public void setDeliverCost(Delivercost deliverCost) {
		this.deliverCost = deliverCost;
	}

	public Set getProductphotos() {
			return productphotos;
	}


	public void setProductphotos(Set productphotos) {
			this.productphotos = productphotos;
	}


 	public Set getPromotions() {
		return promotions;
	}

	public void setPromotions(Set promotions) {
		this.promotions = promotions;
	}

	 public String getCategorySubId() {
			return categorySubId;
		}

		public void setCategorySubId(String categorySubId) {
			this.categorySubId = categorySubId;
		}
	public Set getInventorys() {
				return inventorys;
	}

	public void setInventorys(Set inventorys) {
				this.inventorys = inventorys;
	}

	public Set getOptions() {
		return options;
	}

	public void setOptions(Set options) {
		this.options = options;
	}
	
}


