package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 479971766356610289L;
	private Integer productId;
     private String productName;
     private String size;
     private String color;
     private String detail;
     private int amount;
	 private String unit;
     private float price;
     private String categoryChildId;
     private String categorySubId;
     private int originId;
     private int productTypeId;
     private int manufacturerId;
	 private String account;
	 private Date uploadDate;
	 private Delivercost deliverCost;
	 private int focusId;
	 private int focusOnId;
	 private int marketId;
	 private Date fromDate;
	 private Date toDate;
	 private int transactionInfoId;
    
	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getCategoryChildId() {
        return this.categoryChildId;
    }
    
    public void setCategoryChildId(String categoryChildId) {
        this.categoryChildId = categoryChildId;
    }
    public int getManufacturerId() {
        return this.manufacturerId;
    }
    
    public void setManufacturerId(int manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    public Date getUploadDate() {
		return uploadDate;
	 }
    public int getOriginId() {
		return originId;
	}

	public void setOriginId(int originId) {
		this.originId = originId;
	}

	public int getProductTypeId() {
		return productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}
	
	public Delivercost getDeliverCost() {
		return deliverCost;
	}

	public void setDeliverCost(Delivercost deliverCost) {
		this.deliverCost = deliverCost;
	}

	 public String getCategorySubId() {
			return categorySubId;
		}

	public void setCategorySubId(String categorySubId) {
		this.categorySubId = categorySubId;
	}

	public int getFocusId() {
		return focusId;
	}

	public void setFocusId(int focusId) {
		this.focusId = focusId;
	}

	public int getFocusOnId() {
		return focusOnId;
	}

	public void setFocusOnId(int focusOnId) {
		this.focusOnId = focusOnId;
	}

	public int getMarketId() {
		return marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAccount() {
		return account;
	}

	public void setTransactionInfoId(int transactionInfoId) {
		this.transactionInfoId = transactionInfoId;
	}

	public int getTransactionInfoId() {
		return transactionInfoId;
	}
	
}


