package POJO;

import javax.faces.bean.ManagedBean;

// Generated Aug 2, 2011 4:30:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Bank generated by hbm2java
 */
@ManagedBean
public class SellingMode  implements java.io.Serializable {

	private Integer SellingModeId;
    private User SellingMode;
     
	public SellingMode() {
	}

	public Integer getSellingModeId() {
		return SellingModeId;
	}

	public void setSellingModeId(Integer sellingModeId) {
		SellingModeId = sellingModeId;
	}

	public User getSellingMode() {
		return SellingMode;
	}

	public void setSellingMode(User sellingMode) {
		SellingMode = sellingMode;
	}


}


