package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated Aug 24, 2011 3:21:22 PM by Hibernate Tools 3.2.1.GA



/**
 * Shippingcompany generated by hbm2java
 */
public class Shippingcompany  implements java.io.Serializable {


     private Integer shippingCompanyId;
     private String shippingCompanyName;
     private User seller;
     private String address;     
     private String phone;
     private String fax;
     private String web;
     private String email;
     private Set delivers=new HashSet(0);
     
     public Shippingcompany() {
    }

    public Shippingcompany(String shippingCompanyName, User seller) {
       this.shippingCompanyName = shippingCompanyName;
       this.seller = seller;
    }
    public Shippingcompany(Integer shippingCompanyId,
			String shippingCompanyName, User seller, String address,
			String phone, String fax, String web,String email) {
		this.shippingCompanyId = shippingCompanyId;
		this.shippingCompanyName = shippingCompanyName;
		this.seller = seller;
		this.address = address;
		this.phone = phone;
		this.fax = fax;
		this.web = web;
		this.email=email;
	}

	
   
    public Shippingcompany(Integer shippingCompanyId,
			String shippingCompanyName, User seller, String address,
			String phone, String fax, String web,String email, Set delivers) {
		this.shippingCompanyId = shippingCompanyId;
		this.shippingCompanyName = shippingCompanyName;
		this.seller = seller;
		this.address = address;
		this.phone = phone;
		this.fax = fax;
		this.web = web;
		this.email=email;
		this.delivers = delivers;
		
	}

	public Integer getShippingCompanyId() {
        return this.shippingCompanyId;
    }
    
    public void setShippingCompanyId(Integer shippingCompanyId) {
        this.shippingCompanyId = shippingCompanyId;
    }
    public String getShippingCompanyName() {
        return this.shippingCompanyName;
    }
    
    public void setShippingCompanyName(String shippingCompanyName) {
        this.shippingCompanyName = shippingCompanyName;
    }
    public User getSeller() {
        return this.seller;
    }
    
    public void setSeller(User seller) {
        this.seller = seller;
    }
    
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getWeb() {
		return web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getDelivers() {
		return delivers;
	}

	public void setDelivers(Set delivers) {
		this.delivers = delivers;
	}


}


