package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productorder generated by hbm2java
 */
public class Productorder  implements java.io.Serializable {


     private Integer productOrderId;
     private Transport transport;
     private User user;
     private Stateorder stateorder;
     private float totalMoney;
     private String reciever;
     private Date orderDate;
     private String address;
     private String phone;
     private Set productorderdetails = new HashSet(0);

    public Productorder() {
    }

	
    public Productorder(Transport transport, User user, Stateorder stateorder, float totalMoney, String reciever, Date orderDate, String address, String phone) {
        this.transport = transport;
        this.user = user;
        this.stateorder = stateorder;
        this.totalMoney = totalMoney;
        this.reciever = reciever;
        this.orderDate = orderDate;
        this.address = address;
        this.phone = phone;
    }
    public Productorder(Transport transport, User user, Stateorder stateorder, float totalMoney, String reciever, Date orderDate, String address, String phone, Set productorderdetails) {
       this.transport = transport;
       this.user = user;
       this.stateorder = stateorder;
       this.totalMoney = totalMoney;
       this.reciever = reciever;
       this.orderDate = orderDate;
       this.address = address;
       this.phone = phone;
       this.productorderdetails = productorderdetails;
    }
   
    public Integer getProductOrderId() {
        return this.productOrderId;
    }
    
    public void setProductOrderId(Integer productOrderId) {
        this.productOrderId = productOrderId;
    }
    public Transport getTransport() {
        return this.transport;
    }
    
    public void setTransport(Transport transport) {
        this.transport = transport;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Stateorder getStateorder() {
        return this.stateorder;
    }
    
    public void setStateorder(Stateorder stateorder) {
        this.stateorder = stateorder;
    }
    public float getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(float totalMoney) {
        this.totalMoney = totalMoney;
    }
    public String getReciever() {
        return this.reciever;
    }
    
    public void setReciever(String reciever) {
        this.reciever = reciever;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getProductorderdetails() {
        return this.productorderdetails;
    }
    
    public void setProductorderdetails(Set productorderdetails) {
        this.productorderdetails = productorderdetails;
    }
    public int getTransportId(){
        return this.transport.getTransportId();
    }
    public String getAccount(){
        return this.user.getAccount();
    }



}


