package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated Aug 3, 2011 5:04:51 PM by Hibernate Tools 3.2.1.GA



/**
 * Producttype generated by hbm2java
 */
public class Producttype  implements java.io.Serializable {


     private Integer productTypeId;
     private String productTypeName;
     private Set products = new HashSet(0);

    public Producttype() {
    }

    public Producttype(String productTypeName, Set products) {
       this.productTypeName = productTypeName;
       this.products = products;
    }
   
    public Integer getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }
    public String getProductTypeName() {
        return this.productTypeName;
    }
    
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    public Set getProducts() {
		return products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}



}


