package POJO;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import BUS.CompanyBUS;
import UTIL.MySqlDataAccessHelper;
// Generated Jul 26, 2011 3:52:17 PM by Hibernate Tools 3.2.1.GA



/**
 * Company generated by hbm2java
 */
@SuppressWarnings("serial")
@ManagedBean(name="company")
@SessionScoped
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String companyName;
     private User user=loadUserLogin();
	 private String address;
	 private String representative; 
	 private String businessNumber;
     private String phone;
     private String fax;
     private String businessType;
     private int nationality;
     private String identityCard;
     private Date established;
     private int employees;
     private String mainProduct;
     private String web;
     private String capital;
     private int settlement;
     
 	MySqlDataAccessHelper helper = new MySqlDataAccessHelper();

	public Company() {
    }

	
  
    public Company(Integer companyId, String companyName,
			String address) {
		super();
		this.companyId = companyId;
		this.companyName = companyName;
		this.address = address;
	}



	public Company(String companyName,User user, String address, String representative, String businessNumber, String phone, String fax, String businessType, int nationality, String identityCard, Date established, int employees, String mainProduct, String web, String capital, int settlement) {
       this.companyName = companyName;
       this.businessNumber = businessNumber;
       this.phone = phone;
       this.fax = fax;
       this.user = user;
       this.representative = representative;
       this.address = address;
       this.businessType = businessType;
       this.identityCard = identityCard;
       this.nationality = nationality;
       this.established = established;
       this.employees = employees;
       this.mainProduct = mainProduct;
       this.web = web;
       this.capital = capital;
       this.settlement = settlement;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getRepresentative() {
		return representative;
	}


	public void setRepresentative(String representative) {
		this.representative = representative;
	}


    public String getBusinessNumber() {
        return this.businessNumber;
    }
    
    public void setBusinessNumber(String businessNumber) {
        this.businessNumber = businessNumber;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public User getUser() {
		return user;
	}


	public void setUser(User user) {
		this.user = user;
	}

    public String getAddress() {
		return address;
	}


	public void setAddress(String address) {
		this.address = address;
	}


	public String getBusinessType() {
		return businessType;
	}



	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}



	public int getNationality() {
		return nationality;
	}



	public void setNationality(int nationality) {
		this.nationality = nationality;
	}



	public String getIdentityCard() {
		return identityCard;
	}



	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}


	public Date getEstablished() {
		return established;
	}



	public void setEstablished(Date date) {
		this.established = date;
	}



	public int getEmployees() {
		return employees;
	}



	public void setEmployees(int employees) {
		this.employees = employees;
	}



	public String getMainProduct() {
		return mainProduct;
	}



	public void setMainProduct(String mainProduct) {
		this.mainProduct = mainProduct;
	}



	public String getWeb() {
		return web;
	}



	public void setWeb(String web) {
		this.web = web;
	}



	public String getCapital() {
		return capital;
	}



	public void setCapital(String capital) {
		this.capital = capital;
	}



	public int getSettlement() {
		return settlement;
	}



	public void setSettlement(int settlement) {
		this.settlement = settlement;
	}
	
	public User loadUserLogin(){
		FacesContext f=FacesContext
		.getCurrentInstance();
		HttpSession session= (HttpSession) f.getExternalContext().getSession(true);
		return (session.getAttribute("uselogin")!=null) ? (User) session.getAttribute("uselogin") : user;
	}

	@Override
	public String toString() {
		return this.companyName;
	}


	// get company infor by customer account
	public Company getCompanyByUserAccount(){
		return CompanyBUS.getCompanySell(user.getAccount(),"MALL_LA");
	}
	
	
	// get all company
//	public List<Company> getAllCompany(String lang){
//		List<Company> list = new ArrayList<Company>();
//		try {
//			helper.open(lang);
//			String sql = "Select * from company";
//			ResultSet rs = helper.executeQuery(sql);
//			while(rs.next()){
//				Company com = new Company(rs.getInt("CompanyID"),rs.getString("CompanyName"),rs.getString("Address"));
//				list.add(com);
//				System.out.println("CompanyID : " + com.getCompanyId());
//				System.out.println("CompanyName : " + com.getCompanyName());
//				System.out.println("Address : " + com.getAddress());
//			}
//		} catch (Exception e) {
//		}
//		return list;
//	}
//	public static void main(String[] args) {
//		Company company = new Company();
//		company.getAllCompany("MALL_VN");
//		System.out.println("Infor Company : "+company.getCompanyByUserAccount());
//	}
	
}


