package POJO;
// Generated Sep 19, 2011 9:56:00 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Emailconfigure generated by hbm2java
 */
public class Emailconfigure  implements java.io.Serializable {


     private int emailConfigureId;
     private String ssl;
     private String email;
     private String password;
     private int portNumber;
     private String hostName;
     private String emailName;
     private Date dateInserted;
     private Date dateLastUpdated;
     private String userInserted;
     private String userLastUpdated;

    public Emailconfigure() {
    }

	
    public Emailconfigure(int emailConfigureId, String ssl, String email, String password, int portNumber, String hostName) {
        this.emailConfigureId = emailConfigureId;
        this.ssl = ssl;
        this.email = email;
        this.password = password;
        this.portNumber = portNumber;
        this.hostName = hostName;
    }
    public Emailconfigure(int emailConfigureId, String ssl, String email, String password, int portNumber, String hostName, String emailName, Date dateInserted, Date dateLastUpdated, String userInserted, String userLastUpdated) {
       this.emailConfigureId = emailConfigureId;
       this.ssl = ssl;
       this.email = email;
       this.password = password;
       this.portNumber = portNumber;
       this.hostName = hostName;
       this.emailName = emailName;
       this.dateInserted = dateInserted;
       this.dateLastUpdated = dateLastUpdated;
       this.userInserted = userInserted;
       this.userLastUpdated = userLastUpdated;
    }
   
    public int getEmailConfigureId() {
        return this.emailConfigureId;
    }
    
    public void setEmailConfigureId(int emailConfigureId) {
        this.emailConfigureId = emailConfigureId;
    }
    public String getSsl() {
        return this.ssl;
    }
    
    public void setSsl(String ssl) {
        this.ssl = ssl;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPortNumber() {
        return this.portNumber;
    }
    
    public void setPortNumber(int portNumber) {
        this.portNumber = portNumber;
    }
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    public String getEmailName() {
        return this.emailName;
    }
    
    public void setEmailName(String emailName) {
        this.emailName = emailName;
    }
    public Date getDateInserted() {
        return this.dateInserted;
    }
    
    public void setDateInserted(Date dateInserted) {
        this.dateInserted = dateInserted;
    }
    public Date getDateLastUpdated() {
        return this.dateLastUpdated;
    }
    
    public void setDateLastUpdated(Date dateLastUpdated) {
        this.dateLastUpdated = dateLastUpdated;
    }
    public String getUserInserted() {
        return this.userInserted;
    }
    
    public void setUserInserted(String userInserted) {
        this.userInserted = userInserted;
    }
    public String getUserLastUpdated() {
        return this.userLastUpdated;
    }
    
    public void setUserLastUpdated(String userLastUpdated) {
        this.userLastUpdated = userLastUpdated;
    }




}


