package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated Aug 19, 2011 4:27:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Invenstate generated by hbm2java
 */
public class Invenstate  implements java.io.Serializable {


     private int stateId;
     private String stateName;
     private Set inventorys = new HashSet(0);

     
    public Invenstate() {
    }

	
    public Invenstate(int stateId) {
        this.stateId = stateId;
    }
    public Invenstate(int stateId, String stateName) {
       this.stateId = stateId;
       this.stateName = stateName;
    }
    
    public Invenstate(int stateId, String stateName, Set inventorys) {
        this.stateId = stateId;
        this.stateName = stateName;
        this.inventorys =  inventorys;
     }
   
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    public Set getInventorys() {
		return inventorys;
	}

	public void setInventorys(Set inventorys) {
		this.inventorys = inventorys;
	}


}


