package POJO;
// Generated Aug 19, 2011 4:27:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private int inventoryId;
     private int productId;
     private int sateId;
     private Date limitDate;

    

	public Inventory() {
    }

	
    public Inventory(int inventoryId, int productId, int sateId, Date limitDate) {
        this.inventoryId = inventoryId;
        this.productId = productId;
        this.sateId = sateId;
        this.limitDate = limitDate;
    }
    
   
    public int getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(int inventoryId) {
        this.inventoryId = inventoryId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
  
    public int getSateId() {
        return this.sateId;
    }
    
    public void setSateId(int sateId) {
        this.sateId = sateId;
    }
   
    public Date getLimitDate() {
		return limitDate;
	}


	public void setLimitDate(Date limitDate) {
		this.limitDate = limitDate;
	}



}


