package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA



/**
 * Newsphotos generated by hbm2java
 */
public class Newsphotos  implements java.io.Serializable {


     private Integer newsPhotoId;
     private News news;
     private String newsPhotoName;

    public Newsphotos() {
    }

    public Newsphotos(News news, String newsPhotoName) {
       this.news = news;
       this.newsPhotoName = newsPhotoName;
    }
   
    public Integer getNewsPhotoId() {
        return this.newsPhotoId;
    }
    
    public void setNewsPhotoId(Integer newsPhotoId) {
        this.newsPhotoId = newsPhotoId;
    }
    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }
    public String getNewsPhotoName() {
        return this.newsPhotoName;
    }
    
    public void setNewsPhotoName(String newsPhotoName) {
        this.newsPhotoName = newsPhotoName;
    }




}


