package POJO;
// Generated Sep 28, 2011 9:59:57 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * NlPayment generated by hbm2java
 */
public class NLPayment  implements java.io.Serializable {


     private Integer nlPayment;
     private int orderDetailId;
     private String transactionInfo;
     private String paymentId;
     private String paymentType;
     private String orderCode;
     private Date createDate;
     private Date updateDate;
     private String refundPayment;


    public NLPayment() {
    }

	
    public NLPayment(int orderDetailId, String transactionInfo, String paymentId, String paymentType, String orderCode, Date createDate) {
        this.orderDetailId = orderDetailId;
        this.transactionInfo = transactionInfo;
        this.paymentId = paymentId;
        this.paymentType = paymentType;
        this.orderCode = orderCode;
        this.createDate = createDate;
    }
    public NLPayment(int orderDetailId, String transactionInfo, String paymentId, String paymentType, String orderCode, Date createDate, Date updateDate) {
       this.orderDetailId = orderDetailId;
       this.transactionInfo = transactionInfo;
       this.paymentId = paymentId;
       this.paymentType = paymentType;
       this.orderCode = orderCode;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
    public Integer getNlPayment() {
        return this.nlPayment;
    }
    
    public void setNlPayment(Integer nlPayment) {
        this.nlPayment = nlPayment;
    }
    public int getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public String getTransactionInfo() {
        return this.transactionInfo;
    }
    
    public void setTransactionInfo(String transactionInfo) {
        this.transactionInfo = transactionInfo;
    }
    public String getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public String getOrderCode() {
        return this.orderCode;
    }
    
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }


	public String getRefundPayment() {
		return refundPayment;
	}


	public void setRefundPayment(String refundPayment) {
		this.refundPayment = refundPayment;
	}


}


