package POJO;
// Generated Jul 26, 2011 2:51:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notice generated by hbm2java
 */
public class Notice  implements java.io.Serializable {


     private int noticeId;
     private Typenotice typenotice;
     private User user;
     private Date dateNotice;
     private String contentNotice;
     private String title;
     

    public Notice() {
    }

	
 
    public Notice(int noticeId, Typenotice typenotice, User user, Date dateNotice, String contentNotice, String title) {
       this.noticeId = noticeId;
       this.typenotice = typenotice;
       this.user = user;
       this.dateNotice = dateNotice;
       this.contentNotice = contentNotice;
       this.title = title;
      
    }
   
    public int getNoticeId() {
        return this.noticeId;
    }
    
    public void setNoticeId(int noticeId) {
        this.noticeId = noticeId;
    }
    public Typenotice getTypenotice() {
        return this.typenotice;
    }
    
    public void setTypenotice(Typenotice typenotice) {
        this.typenotice = typenotice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDateNotice() {
        return this.dateNotice;
    }
    
    public void setDateNotice(Date dateNotice) {
        this.dateNotice = dateNotice;
    }
    public String getContentNotice() {
        return this.contentNotice;
    }
    
    public void setContentNotice(String contentNotice) {
        this.contentNotice = contentNotice;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
  



}


