package POJO;
// Generated Aug 27, 2011 3:20:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ordercancel generated by hbm2java
 */
public class Ordercancel  implements java.io.Serializable {

     private int orderCancelId;
     private int orderDetaiId;
     private Date requestDate;
     private Date complete;
     private int cancelStatusId;
     private String cancelCause;
     private String object;
     private String memo;
     private float cancellationPenalty;
     private Date updateDate;

    
	public Ordercancel() {
    }

	
    public Ordercancel(int orderCancelId, int orderDetaiId, int cancelStatusId) {
        this.orderCancelId = orderCancelId;
        this.orderDetaiId = orderDetaiId;
        this.cancelStatusId = cancelStatusId;
    }
    public Ordercancel(int orderCancelId, int orderDetaiId, Date requestDate, Date complete, int cancelStatusId, String cancelCause, String object,String memo) {
       this.orderCancelId = orderCancelId;
       this.orderDetaiId = orderDetaiId;
       this.requestDate = requestDate;
       this.complete = complete;
       this.cancelStatusId = cancelStatusId;
       this.cancelCause = cancelCause;
       this.object = object;
       this.memo=memo;
    }
   
    public int getOrderCancelId() {
        return this.orderCancelId;
    }
    
    public void setOrderCancelId(int orderCancelId) {
        this.orderCancelId = orderCancelId;
    }
    public int getOrderDetaiId() {
        return this.orderDetaiId;
    }
    
    public void setOrderDetaiId(int orderDetaiId) {
        this.orderDetaiId = orderDetaiId;
    }
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    public Date getComplete() {
        return this.complete;
    }
    
    public void setComplete(Date complete) {
        this.complete = complete;
    }
    public int getCancelStatusId() {
        return this.cancelStatusId;
    }
    
    public void setCancelStatusId(int cancelStatusId) {
        this.cancelStatusId = cancelStatusId;
    }
    public String getCancelCause() {
        return this.cancelCause;
    }
    
    public void setCancelCause(String cancelCause) {
        this.cancelCause = cancelCause;
    }
    
    public String getObject() {
		return object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public float getCancellationPenalty() {
		return cancellationPenalty;
	}

	public void setCancellationPenalty(float cancellationPenalty) {
		this.cancellationPenalty = cancellationPenalty;
	}


	public Date getUpdateDate() {
		return updateDate;
	}


	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}	
	

}


