package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated Aug 3, 2011 5:04:51 PM by Hibernate Tools 3.2.1.GA



/**
 * Origin generated by hbm2java
 */
public class Origin  implements java.io.Serializable {


     private Integer originId;
     private String originName;
     private Set products = new HashSet(0);
     private Set companys = new HashSet(0);

 

	

	public Origin() {
    }

    public Origin(String originName, Set products,  Set companys) {
       this.originName = originName;
       this.products = products;
       this.companys = companys;
    }
   
    public Integer getOriginId() {
        return this.originId;
    }
    
    public void setOriginId(Integer originId) {
        this.originId = originId;
    }
    public String getOriginName() {
        return this.originName;
    }
    
    public void setOriginName(String originName) {
        this.originName = originName;
    }

    public Set getProducts() {
		return products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getCompanys() {
		return companys;
	}

	public void setCompanys(Set companys) {
		this.companys = companys;
	}

}


