package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated Sep 8, 2011 9:36:55 AM by Hibernate Tools 3.2.1.GA



/**
 * Paymentmethod generated by hbm2java
 */
public class Paymentmethod  implements java.io.Serializable {


     private Integer paymentMethodId;
     private String paymentMethodName;
     private Set payments = new HashSet(0);
     
    public Paymentmethod() {
    }

    public Paymentmethod(String paymentMethodName) {
       this.paymentMethodName = paymentMethodName;
    }
    
    public Paymentmethod(String paymentMethodName, Set payments) {
        this.paymentMethodName = paymentMethodName;
        this.payments = payments;
     }
   
    public Set getPayments() {
		return payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

	public Integer getPaymentMethodId() {
        return this.paymentMethodId;
    }
    
    public void setPaymentMethodId(Integer paymentMethodId) {
        this.paymentMethodId = paymentMethodId;
    }
    public String getPaymentMethodName() {
        return this.paymentMethodName;
    }
    
    public void setPaymentMethodName(String paymentMethodName) {
        this.paymentMethodName = paymentMethodName;
    }




}


