package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated Aug 27, 2011 3:20:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Cancelstatus generated by hbm2java
 */
public class Cancelstatus  implements java.io.Serializable {


     private Integer cancelStatusId;
     private String cancelStatusName;
     private Set ordercancels = new HashSet(0);

	public Cancelstatus() {
    }

    public Cancelstatus(String cancelStatusName) {
       this.cancelStatusName = cancelStatusName;
    }
    
    public Cancelstatus(String cancelStatusName, Set ordercancels) {
        this.cancelStatusName = cancelStatusName;
        this.ordercancels = ordercancels;
     }
   
    public Integer getCancelStatusId() {
        return this.cancelStatusId;
    }
    
    public void setCancelStatusId(Integer cancelStatusId) {
        this.cancelStatusId = cancelStatusId;
    }
    public String getCancelStatusName() {
        return this.cancelStatusName;
    }
    
    public void setCancelStatusName(String cancelStatusName) {
        this.cancelStatusName = cancelStatusName;
    }
    
    public Set getOrdercancels() {
		return ordercancels;
	}

	public void setOrdercancels(Set ordercancels) {
		this.ordercancels = ordercancels;
	}



}


