package POJO;
// Generated Aug 26, 2011 1:25:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Extension generated by hbm2java
 */
public class Extension  implements java.io.Serializable {


     private Integer extensionId;
     private int productId;
     private Date limitDateOld;
     private int limitDateNum;
     private Float charge;
     private String status;

    public Extension() {
    }

	
    public Extension(int productId) {
        this.productId = productId;
    }
    public Extension(int productId, Date limitDateOld, int limitDateNum, Float charge,String status) {
       this.productId = productId;
       this.limitDateOld = limitDateOld;
       this.limitDateNum = limitDateNum;
       this.charge = charge;
       this.status = status;
    }
   
    public int getLimitDateNum() {
		return limitDateNum;
	}


	public void setLimitDateNum(int limitDateNum) {
		this.limitDateNum = limitDateNum;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public Integer getExtensionId() {
        return this.extensionId;
    }
    
    public void setExtensionId(Integer extensionId) {
        this.extensionId = extensionId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Date getLimitDateOld() {
        return this.limitDateOld;
    }
    
    public void setLimitDateOld(Date limitDateOld) {
        this.limitDateOld = limitDateOld;
    }
   
    public Float getCharge() {
        return this.charge;
    }
    
    public void setCharge(Float charge) {
        this.charge = charge;
    }




}


