package POJO;

import java.util.HashSet;
import java.util.Set;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA



/**
 * Manufacturer generated by hbm2java
 */
public class Manufacturer  implements java.io.Serializable {


     private Integer manufacturerId;
     private String manufacturerName;
     //private String address;
     //private String phone;
     private Set products = new HashSet(0);

    public Manufacturer() {
    }

    public Manufacturer(String manufacturerName) {
       this.manufacturerName = manufacturerName;
       //this.address = address;
       //this.phone = phone;
    }
    
    public Manufacturer(String manufacturerName, Set products) {
        this.manufacturerName = manufacturerName;
        //this.address = address;
        //this.phone = phone;
        this.products = products;
     }
   
    public Integer getManufacturerId() {
        return this.manufacturerId;
    }
    
    public void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }
    public String getManufacturerName() {
        return this.manufacturerName;
    }
    
    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName;
    }
    /*public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }*/
    
    public Set getProducts() {
		return products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}




}


