package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Newscategory generated by hbm2java
 */
public class Newscategory  implements java.io.Serializable {


     private Integer newsCategoryId;
     private String newsCategoryName;
     private Set newses = new HashSet(0);

    public Newscategory() {
    }

	
    public Newscategory(String newsCategoryName) {
        this.newsCategoryName = newsCategoryName;
    }
    public Newscategory(String newsCategoryName, Set newses) {
       this.newsCategoryName = newsCategoryName;
       this.newses = newses;
    }
   
    public Integer getNewsCategoryId() {
        return this.newsCategoryId;
    }
    
    public void setNewsCategoryId(Integer newsCategoryId) {
        this.newsCategoryId = newsCategoryId;
    }
    public String getNewsCategoryName() {
        return this.newsCategoryName;
    }
    
    public void setNewsCategoryName(String newsCategoryName) {
        this.newsCategoryName = newsCategoryName;
    }
    public Set getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set newses) {
        this.newses = newses;
    }




}


