package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Promotions generated by hbm2java
 */
public class Promotions  implements java.io.Serializable {


     private Integer promotionId;
     private int productId;
     private String promotionType;
     private String content;
     private String rate;
     private Date beginDate;
     private Date endtDate;

    public Promotions() {
    }

    public Promotions(int productId, String promotionType, String content, String rate, Date beginDate, Date endtDate) {
       this.productId = productId;
       this.promotionType = promotionType;
       this.content = content;
       this.rate = rate;
       this.beginDate = beginDate;
       this.endtDate = endtDate;
    }
   
    public Integer getPromotionId() {
        return this.promotionId;
    }
    
    public void setPromotionId(Integer promotionId) {
        this.promotionId = promotionId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getPromotionType() {
        return this.promotionType;
    }
    
    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndtDate() {
        return this.endtDate;
    }
    
    public void setEndtDate(Date endtDate) {
        this.endtDate = endtDate;
    }




}


