package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Stateorder generated by hbm2java
 */
public class Stateorder  implements java.io.Serializable {


     private Integer stateOrderId;
     private String stateOrderName;
     private Set productorders = new HashSet(0);

    public Stateorder() {
    }

	
    public Stateorder(String stateOrderName) {
        this.stateOrderName = stateOrderName;
    }
    public Stateorder(String stateOrderName, Set productorders) {
       this.stateOrderName = stateOrderName;
       this.productorders = productorders;
    }
   
    public Integer getStateOrderId() {
        return this.stateOrderId;
    }
    
    public void setStateOrderId(Integer stateOrderId) {
        this.stateOrderId = stateOrderId;
    }
    public String getStateOrderName() {
        return this.stateOrderName;
    }
    
    public void setStateOrderName(String stateOrderName) {
        this.stateOrderName = stateOrderName;
    }
    
    public Set getProductorders() {
        return this.productorders;
    }
    
    public void setProductorders(Set productorders) {
        this.productorders = productorders;
    }




}


