package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA



/**
 * Thamso generated by hbm2java
 */
public class Thamso  implements java.io.Serializable {


     private String key;
     private Integer value;
     private String description;
 


	public Thamso() {
    }

    public Thamso(String key, Integer value, String description) {
       this.key = key;
       this.value = value;
       this.description = description;
    }

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public Integer getValue() {
		return value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
   
    


 


}


