package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Transport generated by hbm2java
 */
public class Transport  implements java.io.Serializable {


     private Integer transportId;
     private String transportName;
     private Set productorders = new HashSet(0);

    public Transport() {
    }

	
    public Transport(String transportName) {
        this.transportName = transportName;
    }
    public Transport(String transportName, Set productorders) {
       this.transportName = transportName;
       this.productorders = productorders;
    }
   
    public Integer getTransportId() {
        return this.transportId;
    }
    
    public void setTransportId(Integer transportId) {
        this.transportId = transportId;
    }
    public String getTransportName() {
        return this.transportName;
    }
    
    public void setTransportName(String transportName) {
        this.transportName = transportName;
    }
 
    public Set getProductorders() {
        return this.productorders;
    }
    
    public void setProductorders(Set productorders) {
        this.productorders = productorders;
    }




}


